name: laravel
services:
  app:
    build:
      context: ../
      dockerfile: DockerfileLaravel
    restart: always
    
    env_file:
      - ./laravel-app.env
    ports:
      - 9000:9000
    

  web:
    build:
      context: ../
      dockerfile: DockerfileNginx
    container_name: laravel-nginx
    restart: always
    ports:
      - "8080:80"
    
    
  db:
    image: postgres:18.0-alpine3.22
    container_name: laravel-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: